// This file is auto-generated by @hey-api/openapi-ts

export type Bill = {
    id?: string;
    amount?: number;
    date?: string;
    tableId?: string;
    products?: Array<{
        productId?: string;
        quantity?: number;
    }>;
};

export type Category = {
    id?: string;
    name?: string;
    description?: string;
};

export type CreateBillRequest = {
    amount: number;
    date: string;
    tableId: string;
    products: Array<{
        productId?: string;
        quantity?: number;
    }>;
};

export type CreateCategoryRequest = {
    name: string;
    description?: string;
};

export type CreateProductRequest = {
    name: string;
    price: number;
};

export type CreateTableRequest = {
    number: number;
};

export type Error = {
    code?: number;
    message?: string;
};

export type ParameterbillId = string;

export type ParametercategoryId = string;

export type ParameterproductId = string;

export type ParametertableId = string;

export type Product = {
    id?: string;
    name?: string;
    price?: number;
};

export type SplitBillRequest = {
    splits?: Array<{
        products?: Array<{
            productId?: string;
            quantity?: number;
        }>;
    }>;
};

export type Table = {
    id?: string;
    number?: number;
};

export type UpdateBillRequest = {
    amount?: number;
    date?: string;
    tableId?: string;
    products?: Array<{
        productId?: string;
        quantity?: number;
    }>;
};

export type UpdateCategoryRequest = {
    name?: string;
    description?: string;
};

export type UpdateProductRequest = {
    name?: string;
    price?: number;
};

export type UpdateTableRequest = {
    number?: number;
};