// This file is auto-generated by @hey-api/openapi-ts

export type Bill = {
    id?: string;
    amount?: number;
    date?: string;
    tableId?: string;
    paid?: boolean;
    guests?: (number) | null;
    openedAt?: (string) | null;
    lastOrderAt?: (string) | null;
    products?: Array<{
        productId?: string;
        name?: string;
        quantity?: number;
        unitPrice?: number;
    }>;
};

export type Category = {
    id?: string;
    name?: string;
    description?: string;
};

export type CreateBillRequest = {
    amount: number;
    date: string;
    guests?: number;
    tableId: string;
    products: Array<{
        productId?: string;
        quantity?: number;
    }>;
};

export type CreateCategoryRequest = {
    name: string;
    description?: string;
};

export type CreateProductRequest = {
    name: string;
    price: number;
    imageUrl?: string;
};

export type CreateTableRequest = {
    number: number;
    name?: string;
    capacity?: number;
};

export type DailyReport = {
    date?: string;
    revenue?: number;
    openAmount?: number;
    billsPaid?: number;
    billsOpen?: number;
    guestsServed?: number;
    averageTicket?: number;
    hourly?: Array<{
        hour?: number;
        revenue?: number;
        bills?: number;
    }>;
    topProducts?: Array<{
        name?: string;
        imageUrl?: (string) | null;
        quantity?: number;
        revenue?: number;
    }>;
    categories?: Array<{
        name?: string;
        revenue?: number;
    }>;
};

export type Error = {
    code?: number;
    message?: string;
};

export type ParameterbillId = string;

export type ParametercategoryId = string;

export type ParameterproductId = string;

export type ParametertableId = string;

export type Product = {
    id?: string;
    name?: string;
    price?: number;
    categoryId?: string;
    imageUrl?: string;
};

export type ProductReport = {
    productId?: string;
    unitsSold?: number;
    revenue?: number;
    billsSold?: number;
    lastSoldAt?: (string) | null;
    unitsOpen?: number;
    tablesOpen?: number;
};

export type SplitBillRequest = {
    splits?: Array<{
        products?: Array<{
            productId?: string;
            quantity?: number;
        }>;
    }>;
};

export type Table = {
    id?: string;
    number?: number;
    name?: (string) | null;
    capacity?: number;
    activeBills?: Array<Bill> | null;
};

export type UpdateBillRequest = {
    amount?: number;
    date?: string;
    tableId?: string;
    paid?: boolean;
    guests?: (number) | null;
    products?: Array<{
        productId?: string;
        quantity?: number;
    }>;
};

export type UpdateCategoryRequest = {
    name?: string;
    description?: string;
};

export type UpdateProductRequest = {
    name?: string;
    price?: number;
    imageUrl?: string;
};

export type UpdateTableRequest = {
    number?: number;
    name?: string;
    capacity?: number;
};