// This file is auto-generated by @hey-api/openapi-ts

export type Bill = {
    id?: string;
    amount?: number;
    date?: string;
    products?: Array<{
        productId?: string;
        quantity?: number;
    }>;
    tableId?: string;
};

export type CreateBillRequest = {
    amount: number;
    date: string;
    /**
     * ID of the table associated with this bill
     */
    tableId: TableId;
    products: Array<{
        productId?: ProductId;
        quantity?: number;
    }>;
};

export type CreateProductRequest = {
    name: string;
    price: number;
};

export type CreateTableRequest = {
    number: number;
};

export type Error = {
    code?: number;
    message?: string;
};

export type ParameterbillId = string;

export type ParameterproductId = string;

export type ParametertableId = string;

export type Product = {
    id?: string;
    name?: string;
    price?: number;
};

export type ProductId = string;

export type ProductSplit = {
    productId: string;
    quantity: number;
};

export type Split = {
    products: Array<ProductSplit>;
};

export type SplitBillRequest = {
    splits: Array<Split>;
};

export type Table = {
    id?: string;
    number?: number;
};

export type TableId = string;

export type UpdateBillRequest = {
    amount?: number;
    date?: string;
    products?: Array<{
        productId?: string;
        quantity?: number;
    }>;
    tableId?: string;
};

export type UpdateProductRequest = {
    name?: string;
    price?: number;
};

export type UpdateTableRequest = {
    number?: number;
};

export type BillId = ParameterbillId;
