Table products {
    id uuid [pk]
    name varchar
    price numeric
}

Table tables {
    id uuid [pk]
    number int
}

Table bills {
    id uuid [pk]
    amount numeric
    date date
    table_id uuid [ref: > tables.id]
}

Table bill_items {
    bill_id uuid [ref: > bills.id]
    product_id uuid [ref: > products.id]
    quantity int
    unit_price numeric
    created_at datetime 
    updated_at datetime
    status varchar
    primary key(bill_id, product_id)
}
