name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Build & Test
        run: mvn clean verify
        working-directory: contappa-core
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: contappa-core

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Run OpenAPI linting
        run: redocly lint doc/openapi.yaml --format=github-actions
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Newman
        run: npm install -g newman
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Run Integration Tests
        run: make ci-tests
