name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: maven
            - name: Build & Test
              run: mvn clean verify
              working-directory: contappa-core
    checkstyle:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: maven

            - name: Run Checkstyle
              run: mvn checkstyle:check
              working-directory: contappa-core
